version: '3.4'
services:
    bind9:
        image: drehtuer/bind9:latest
        deploy:
            labels:
                - "traefik.enable=false"
            mode: global
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/data/docker/config/bind9:/etc/named:ro
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        secrets:
            - source: bind_rndc
              target: rndc.key
              mode: 0444
        networks:
            traefik-net:

    traefik:
        image: traefik:latest
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.backend=traefik-ui"
                - "traefik.network=rlyeh_traefik-net"
                - "traefik.frontend.rule=Host:cloud.drehtuer.net"
                - "traefik.port=9001"
            mode: global
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/data/docker/config/traefik:/etc/traefik:ro
            - /var/data/docker/persist/traefik/acme.json:/data/acme.json
        ports:
            - "80:80/tcp"
            - "443:443/tcp"
        networks:
            traefik-net:

    portainer:
        image: portainer/portainer:latest
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.backend=portainer"
                - "traefik.network=rlyeh_traefik-net"
                - "traefik.frontend.rule=PathPrefixStrip:/portainer/"
                - "traefik.port=9000"
            mode: global
            placement:
                constraints:
                    [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/data/docker/persist/portainer:/data
        networks:
            traefik-net:

networks:
    traefik-net:
        driver: overlay
        driver_opts:
            encrypted: "true"

secrets:
    bind_rndc:
        file: /var/data/docker/secrets/rndc.key
