version: "3.4"
services:
    bind9:
        image: drehtuer/bind9:latest
        deploy:
            labels:
                - "traefik.enable=false"
            mode: global
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/data/docker/config/bind9:/etc/named:ro
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        secrets:
            - source: bind_rndc
              target: rndc.key
              mode: 0444
        networks:
            net_internal:
                aliases:
                    - internal_bind9

    traefik:
        image: traefik:latest
        deploy:
            labels:
                - "traefik.enable=false"
            mode: global
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - /var/data/docker/config/traefik:/etc/traefik:ro
            - /var/data/docker/persist/traefik/acme.json:/data/acme.json:rw
        ports:
            - "80:80/tcp"
            - "443:443/tcp"
        networks:
            net_traefik:
                aliases:
                    - traefik_traefik

    nginx:
        image: nginx:latest
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.port=80"
                - "traefik.backend=nginx"
                - "traefik.docker.network=rlyeh_net_traefik"
                - "traefik.frontend.rule=Host:www.drehtuer.net,drehtuer.net"
                - "traefik.frontend.priority=5"
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        volumes:
            - /var/data/docker/config/nginx:/etc/nginx:ro
            - /var/data/docker/static/srv/www:/srv/www:ro
        networks:
            net_traefik:
                aliases:
                    - traefik_nginx

    portainer:
        image: portainer/portainer:latest
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.port=9000"
                - "traefik.backend=portainer"
                - "traefik.docker.network=rlyeh_net_traefik"
                - "traefik.frontend.rule=PathPrefixStrip:/portainer"
                - "traefik.frontend.priority=10"
            mode: global
            placement:
                constraints:
                    [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/data/docker/persist/portainer:/data
        networks:
            net_traefik:
                aliases:
                    - traefik_portainer

    redis:
        image: redis:latest
        deploy:
            labels:
                - "traefik.enable=false"
            mode: global
            placement:
                constraints:
                    [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/data/docker/persist/redis:/data:rw
        command: redis-server --appendonly yes
        networks:
            net_internal:
                aliases:
                    - internal_redis

    ethercalc:
        image: audreyt/ethercalc:latest
        depends_on:
            - redis
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.port=8000"
                - "traefik.backend=ethercalc"
                - "traefik.docker.network=rlyeh_net_traefik"
                - "traefik.frontend.rule=PathPrefixStrip:/ethercalc"
                - "traefik.frontend.priority=10"
            mode: global
            restart_policy:
                condition: on-failure
        command: sh -c "REDIS_HOST=internal_redis REDIS_PORT=6379 pm2 start `which ethercalc` -x -- --expire 7776000 --basepath /ethercalc && pm2 logs"
        networks:
            net_internal:
                aliases:
                    - internal_ethercalc
            net_traefik:
                aliases:
                    - traefik_ethercalc

    teamspeak:
        image: drehtuer/teamspeak:latest
        deploy:
            labels:
                - "traefik.enable=false"
            mode: global
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/data/docker/config/teamspeak/ts3server.ini:/teamspeak3-server_linux_amd64/ts3server.ini:ro
            - /var/data/docker/config/teamspeak/ts3db_mariadb.ini:/teamspeak3-server_linux_amd64/ts3db_mariadb.ini:ro
            - /var/data/docker/persist/teamspeak/files:/teamspeak3-server_linux_amd64/files:rw
            - /var/data/docker/persist/teamspeak/logs:/teamspeak3-server_linux_amd64/logs:rw
        ports:
            - "9987:9987/udp"
            - "3033:30033/tcp"
            - "10011:10011/tcp"
        networks:
            net_internal:
                aliases:
                    - internal_teamspeak

    mariadb:
        image: mariadb:latest
        deploy:
            labels:
                - "traefik.enable=false"
            mode: global
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb.passwd
        secrets:
            - source: mariadb_root_passwd
              target: mariadb.passwd
              mode: 0444
        volumes:
            - /var/data/docker/config/mariadb/conf.d:/etc/mysql/conf.d:ro
            - /var/data/docker/persist/mariadb:/var/lib/mysql:rw
        networks:
            net_internal:
                aliases:
                    - internal_mariadb

    chrony:
        image: drehtuer/chrony:latest
        deploy:
            labels:
                - "traefik.enable=false"
            mode: global
            restart_policy:
                condition: on-failure
        volumes:
            - /var/data/docker/config/chrony:/etc/chrony:ro
            - /var/data/docker/persist/chrony:/var/lib/chrony:rw

    postfix:
        image: drehtuer/postfix:latest
        deploy:
            labels:
                - "traefik.enable=false"
            mode: global
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/data/docker/postfix:/etc/postfix:ro
        ports:
            - "25:25/tcp"
            - "587:587/tcp"
        networks:
            net_internal:
                aliases:
                    - internal_postfix

    dovecot:
        image: drehtuer/dovecot:latest
        deploy:
            labels:
                - "traefik.enable=false"
            mode: global
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        volumes:
            - /var/data/docker/dovecot:/etc/dovecot:ro
        ports:
            - "993:993/tcp"
        networks:
            net_internal:
                aliases:
                    - internal_dovecot

networks:
    net_traefik:
        driver: overlay
        driver_opts:
            encrypted: "true"

    net_internal:
        driver: overlay
        driver_opts:
            encrypted: "true"

secrets:
    bind_rndc:
        file: /var/data/docker/secrets/rndc.key
    mariadb_root_passwd:
        file: /var/data/docker/secrets/mariadb.key
